callumalpass/tasknotes

src/services/FilterService.ts, src/types.ts, src/views/KanbanView.ts
- Add GetGroupedTasksOptions interface to support target date and pre-population of groups
- Update FilterService to utilize new options in getGroupedTasks method
- Modify KanbanView to pass options for improved task grouping and display
=> feat: Introduce GetGroupedTasksOptions for enhanced task grouping

src/services/PomodoroService.ts
Fixes #293
This pull request fixes a bug in the Pomodoro timer where the manually adjusted duration was ignored when starting the countdown.
=> Fix #293 Ensure timer starts with adjusted duration

.gitignore, copy-files.mjs, src/views/TaskListView.ts, styles/task-list-view.css
**What**
Allow users to collapse and expand groups in the task list. 
Task List view only. Agenda collapsible groups will be a separate PR.
**src/views/TaskListView.ts** and **styles/task-list-view.css only.**
**Why**
When the task list displays many groups, navigating to the desired group requires a lot of scrolling.
Sometimes, having too many tasks and groups open clutters the view and makes it more difficult to focus.
Allow users to keep great context by seeing all groups, but focus attention on a few expanded groups at a time by quickly expanding and collapsing without needing to change filters to do so.
**Demo GIF**
**What’s included**
- Collapsible groups with persisted state (per grouping key + group name) via ViewStateManager.
- Renders button.task-group-toggle with Obsidian’s …
=> feat(tasklist): collapsible groups (chevron + persisted state) [3.19.1]

src/services/ICSNoteService.ts, src/settings/defaults.ts, src/settings/settings.ts, src/types/settings.ts, src/utils/filenameGenerator.ts
Adds separate filename template configuration for notes created from calendar events, addressing issue #362.
- **New Settings**: Added `icsNoteFilenameFormat` and `customICSNoteFilenameTemplate` to ICS integration settings
- **Template Options**: Support for title, zettel, timestamp, and custom formats
- **ICS Variables**: Added `{icsEventTitle}`, `{icsEventLocation}`, `{icsEventDescription}`, `{icsEventTitleWithDate}`
- **UI**: Added filename format settings in ICS Integration tab
- **Fix**: `{title}` now uses clean event title instead of "Event Name - Date"
- `{title}` - Clean event title: "Team Meeting"
- `{icsEventTitleWithDate}` - Title with date: "Team Meeting - January 15, 2024"  
- `{icsEventLocation}` - Event location
- `{icsEventDescription}` - Event description
- Plus all …
=> Add filename template support for calendar event notes

src/modals/TaskCreationModal.ts, src/modals/TaskEditModal.ts, src/modals/TaskModal.ts, src/services/TaskService.ts, src/types.ts, styles/task-modal.css, tests/unit/modals/TaskModal.user-fields.test.ts
- Add user field support to task creation and edit modals
- Store user field values as custom frontmatter properties
- Include autocomplete suggestions from existing field values
- Support text, boolean, number, date, and list field types
- Extended TaskModal base class with dynamic user field generation
- Added change detection for edit scenarios
- Implemented UserFieldSuggest for autocomplete functionality
- Added unit tests and CSS styling
=> feat: Add user field support to task creation/edit modals

src/utils/MinimalNativeCache.ts, src/utils/dateUtils.ts, src/utils/helpers.ts
Resolves issue (#455) where notes with custom dateCreated field mapping (e.g., 'created') were ignored, causing plugin to attempt parsing incorrectly formatted fallback date values.
1. **`src/utils/MinimalNativeCache.ts`**
- Updated `getCalendarData()` method to use field mapper for note date extraction
- Updated `getNotesForDate()` method to use field mapper for note date extraction
- Added fallback to hardcoded fields for backward compatibility
2. **`src/utils/helpers.ts`**
- Added `fieldMapper` parameter to `extractNoteInfo()` function
- Updated date extraction logic to use field mapper when available
3. **`src/utils/dateUtils.ts`** 
- Minor formatting changes (line ending normalization)
- **Root Cause:** Plugin was hardcoded to look for `dateCreated`/`date` properties, ignoring user's …
=> fix: (#455) Date parsing errors in console caused by hardcoded mapping not respecting field mapping for note date extraction

docs/settings/calendar-settings.md, src/settings/defaults.ts, src/settings/settings.ts, src/types/settings.ts, src/views/AdvancedCalendarView.ts, styles/task-inline-widget.css
Implements user-configurable calendar locale setting to enable international calendar systems like the Jalali (Persian) calendar.
- ✨ **New Feature**: Calendar locale setting in Settings > Calendar Settings
- 🔧 **Implementation**: Leverages FullCalendar's existing locale support 
- 🌐 **Use Case**: Users can enter locale codes like "fa" for Persian calendar
- 📚 **Documentation**: Updated calendar settings docs
1. Go to Settings > Calendar Settings
2. Enter a locale code (e.g., "fa" for Persian, "de" for German) in "Calendar locale" field
3. Open Advanced Calendar view - dates should display in the selected locale/calendar system
4. Leave empty to auto-detect from browser (default behavior)
Fixes #502
=> Add calendar locale configuration for international calendar support

src/editor/ProjectNoteDecorations.ts, src/main.ts, src/types.ts, src/views/AdvancedCalendarView.ts, src/views/AgendaView.ts, src/views/TaskListView.ts
Fixes recurring daily tasks remaining visually completed after midnight when Obsidian is left open 24/7.
When the date rolls over at midnight, TaskNotes did not refresh task completion states, causing recurring tasks to appear completed for the new day until Obsidian was reloaded.
- Add date change detection with dual timing mechanism (interval + precise midnight timeout)
- Emit EVENT_DATE_CHANGED when date rollover is detected
- All task views and inline widgets automatically refresh when date changes
- Proper event listener cleanup to prevent memory leaks
- Recurring tasks show correct completion state after midnight
- All date-dependent UI elements refresh automatically
- No user action required - works seamlessly in the background
- Handles edge cases like system sleep/wake
Fixes #521
=> Fix: Refresh task states when date changes at midnight

styles/pomodoro-stats-view.css
- Replace undefined `var(--tn-text-error)` with `var(--tn-color-error)` for better contrast
- Fix background color for interrupted session status badges
- Fix text color for negative overview changes
Fixes #499
=> Fix: Improve contrast for INTERRUPTED status badge in pomodoro stats

src/modals/TaskCreationModal.ts, src/services/InstantTaskConvertService.ts, src/services/TaskService.ts, src/utils/TasksPluginParser.ts, src/utils/filenameGenerator.ts
Removes artificial length limits that were truncating task titles during creation.
- Remove 100-character truncation in filename sanitization
- Remove 200-character validation limits across task creation flows
- Add user notification when filename shortening occurs due to filesystem constraints
Tasks with long titles like "This is a very long title. If I use too many characters for it, part of the title will be cut off. This should not be the case." are now preserved in full.
Closes #378
=> Fix title truncation in task creation (#378)

src/services/FilterService.ts, src/types.ts, src/ui/FilterBar.ts
- Adds tags to the sort dropdown for alphabetical sorting by first tag
- Adds tags to the group dropdown with multi-group assignment support
- Tasks with multiple tags appear in multiple groups (like projects)
- Tasks without tags sort last and appear in "No Tags" group
Closes #169
=> feat: add tags to sorting and grouping options (#169)

docs/views/calendar-views.md, src/types.ts, src/views/AdvancedCalendarView.ts
- Adds toggle to show/hide the all-day slot in calendar time grid views
- Resolves scrolling issues when many all-day tasks exist on a single date
- Toggle appears in view options alongside other display controls
=> Add All-day slot toggle to calendar view

src/components/DateContextMenu.ts, src/components/TaskContextMenu.ts
- Add weekday options (Monday-Sunday) to date picker context menus
- Add increment/decrement options (+1/-1 day/week) relative to existing dates
- Organize weekdays in dedicated submenu with separators between option groups
- Enhanced `DateContextMenu` with weekday and increment options
- Integrated enhanced options into `TaskContextMenu` date submenus
- Increment options only appear when existing date is set
- Weekday selection chooses next occurrence (e.g., Monday when today is Monday selects next Monday)
Fixes #238
=> Add more date picker options (weekdays and increment/decrement)

src/services/PomodoroService.ts, src/views/MiniCalendarView.ts, src/views/PomodoroStatsView.ts, src/views/StatsView.ts
Fixes timezone-dependent "Today" identification problems described in issue #452 by implementing proper UTC Anchor Principle compliance throughout the codebase.
**MiniCalendarView** (`src/views/MiniCalendarView.ts:603-605`):
- **Problem**: Used `new Date()` to determine which day to highlight as "today"
- **Fix**: Changed to use `getTodayLocal()` + `createUTCDateFromLocalCalendarDate()` for UTC-anchored today comparison
- **Impact**: Calendar tooltips now correctly identify today across all timezones
**PomodoroService** (`src/services/PomodoroService.ts:891-896`):  
- **Problem**: `getTodayStats()` used `new Date()` instead of UTC-anchored today
- **Fix**: Changed to use UTC-anchored today calculation
- **Impact**: Pomodoro sessions are now correctly categorized as "today" regardless of …
=> fix: resolve UTC Anchor Principle violations causing timezone issues

src/editor/ProjectNoteDecorations.ts, src/services/ViewStateManager.ts, src/ui/FilterBar.ts, src/views/AdvancedCalendarView.ts, src/views/AgendaView.ts, src/views/KanbanView.ts, src/views/TaskListView.ts
- Add property visibility persistence to saved views
- Fix saved view selection to prefer newly created views over older matching ones
- Add proper null safety for FilterBar interactions
- Updated ViewStateManager.saveView() to accept visibleProperties parameter
- Modified all view save handlers to pass property visibility settings
- Fixed detectActiveSavedView() to prefer most recently created views when multiple views match the same filters
- Added setActiveSavedView() method for explicit view activation after saving
Fixes property visibility controls not being persisted when saving filter views.
=> Save property visibility with saved views

src/modals/TaskEditModal.ts, src/services/TaskService.ts, src/utils/helpers.ts
Moves due date when recurring task completed  by the same offset as the original due date is to the original scheduled date to keep same separation
Fixes #470
=> Move Due Date when recurring task completed

src/modals/TaskEditModal.ts, styles/task-modal.css
- Adds clickable project links to the task edit modal
- Users can now directly open project notes from calendar view edit modal without having to open the task note first
- Leverages existing `renderProjectLinks` infrastructure for consistent behavior
- **TaskEditModal.ts**: Override `renderProjectsList` method to make project names clickable using existing link renderer
- **task-modal.css**: Add styling for clickable project links with proper hover effects and visual consistency
- Uses existing `renderProjectLinks` function for robust link handling
- Maintains consistent styling with other views in the application  
- Includes proper error handling and accessibility features
- Preserves existing functionality while adding new clickable behavior
- ✅ TypeScript compilation passes
- ✅ No …
=> feat: add clickable project links in task edit modal

src/services/FieldMapper.ts, tests/unit/services/FieldMapper.boolean-status.test.ts
- Fixes startup crash when templates contain empty `reminders:` property (#583)
- FieldMapper now filters out null/undefined reminders before array creation
- Added comprehensive test coverage for null reminders handling
=> Fix startup crash with empty reminders property

src/main.ts, src/services/AutoArchiveService.ts, src/services/StatusManager.ts, src/services/TaskService.ts, src/settings/defaults.ts, src/settings/tabs/taskPropertiesTab.ts, src/types.ts
Adds configurable auto-archive functionality where tasks can be automatically archived when they reach specific statuses after a timeout period.
- Added `autoArchive` and `autoArchiveDelay` properties to StatusConfig
- Created AutoArchiveService with persistent queue that survives plugin restarts
- Integrated auto-archive triggers with TaskService status change detection  
- Added settings UI for per-status configuration (1-1440 minutes)
- Delay input only shows when auto-archive is enabled
=> Add status-based auto-archive with configurable timeout

src/settings/tabs/appearanceTab.ts, src/ui/TaskCard.ts, tests/unit/ui/TaskCard.test.ts
Fixes two issues with task card property display:
1. **Custom property duplication**: Custom properties appeared twice when configured in both settings and filter bar
2. **Unwanted total tracked time display**: Total tracked time showed even when not enabled and displayed zero values
- Standardize custom property identifiers to use consistent `user:` prefix format
- Remove legacy time tracking fallback that bypassed property visibility settings  
- Add condition to only show total tracked time when value > 0 minutes
- Update tests to reflect corrected behavior
- All existing tests pass
- Added new tests for proper time tracking property behavior
- Verified custom properties no longer duplicate
Users now have proper control over task card property visibility without duplicate or unwanted …
=> Fix custom property duplication and total tracked time visibility

styles/project-note-subtasks.css
I like to have my subtasks at the top of my project notes, but I noticed that there is a cursor shown above the subtasks but jumps to below the subtasks when you start typing.  This leaves a line gap and looks confusing.
This css fixes the issue by setting the CodeMirror widgetBuffer img tag to display: none; if the project-note-subtasks are at the top (or specifically, not at the bottom).
I tested this with both top and bottom display of subtasks and it worked well in my tests.  Oddly enough, if I set it to display: none while at the bottom, the opposite problem occurs (a cursor appears below the subtasks), that is why I look for not last-child.
=> Remove cursor above subtasks when subtasks are set to show at top of project note

README.md, docs/TIMEZONE_HANDLING_GUIDE.md, docs/TIMEZONE_HANDLING_UTC.md, docs/TIMEZONE_QUICK_REFERENCE.md, docs/core-concepts.md, docs/features.md, docs/features/calendar-integration.md, docs/features/ics-integration.md, docs/features/inline-tasks.md, docs/features/integrations.md, docs/features/task-management.md, docs/features/user-fields.md, docs/index.md, docs/nlp-api.md, docs/settings.md, docs/settings/appearance.md, docs/settings/defaults.md, docs/settings/features.md, docs/settings/general.md, docs/settings/integrations.md, docs/settings/task-properties.md, docs/troubleshooting.md, docs/workflows.md, mkdocs.yml
- Fix project name references from "ChronoSync" to "TaskNotes" in timezone documentation
- Correct broken relative paths in settings and features navigation links
- Fix incorrect default task tag reference in troubleshooting documentation
- Updated timezone documentation files to use correct project name
- Fixed 8 broken back navigation links using incorrect relative paths
- Corrected default task tag from "#task" to "task" in troubleshooting guide
- Clarified time-blocking interaction method in calendar integration
- Removed circular function reference in timezone handling guide
All changes maintain neutral tone and improve technical accuracy.
=> docs: fix documentation inaccuracies and broken navigation links

src/bases/base-view-factory.ts, src/bases/helpers.ts, src/editor/ProjectNoteDecorations.ts, src/main.ts, src/services/ProjectSubtasksService.ts, src/services/TaskService.ts, src/services/ViewPerformanceService.ts, src/ui/TaskCard.ts, src/utils/MinimalNativeCache.ts, src/utils/viewOptimizations.ts, src/views/AdvancedCalendarView.ts, src/views/AgendaView.ts, src/views/KanbanView.ts, src/views/TaskListView.ts
Implements comprehensive performance optimizations for TaskNotes views to eliminate full calendar refreshes during task updates.
- **Centralized ViewPerformanceService**: Coordinates updates across all views with debouncing and change detection
- **Selective task updates**: Views update individual task cards instead of full refreshes
- **Event source refresh strategy**: AdvancedCalendarView uses FullCalendar event source refresh instead of manual event manipulation
- **Cross-view optimization**: Prevents cascading refresh avalanches when multiple views are open
- Fixed task properties disappearing in TaskListView after time tracking
- Fixed priority context menu showing stale values after updates  
- Added defensive checks to prevent FullCalendar runtime errors
- Cleaned up excessive …
=> feat: Advanced Calendar Performance Optimization

docs/features/task-management.md, docs/settings/appearance.md, src/modals/ProjectSelectModal.ts, src/settings/defaults.ts, src/settings/tabs/appearanceTab.ts, src/suggest/FileSuggestHelper.ts, src/types/settings.ts, src/utils/projectFilterUtils.ts, tests/unit/modals/ProjectSelectModal.property-filter.test.ts, tests/unit/utils/projectFilterUtils.test.ts
- add optional property key/value filters to project autosuggest settings and defaults
- share filtering logic between project picker and inline suggestions
- document the new filtering fields and cover them with unit tests
=> Add project property filter support

src/services/ProjectSubtasksService.ts, src/utils/MinimalNativeCache.ts
ProjectSubtasksService and MinimalNativeCache were hardcoded to look for `projects` in frontmatter, ignoring user's custom field mapping configuration. This broke subtask/project functionality when users customized their project field name.
- Use `fieldMapper.toUserField('projects')` instead of hardcoded `'projects'`
- Apply fix to both ProjectSubtasksService and MinimalNativeCache
- `src/services/ProjectSubtasksService.ts`
- `src/utils/MinimalNativeCache.ts`
Fixes reported issue where subtask/project functionality wasn't working for users with custom project field mappings.
=> Fix project/subtask functionality to respect user field mapping

src/utils/MinimalNativeCache.ts, tests/unit/utils/MinimalNativeCache.excluded-folders.test.ts
- Fixes parsing of excluded folders when the list ends with trailing commas
- Adds comprehensive tests for various edge cases
Fixes #664
=> Fix trailing commas in excluded folders setting

src/utils/dateUtils.ts, tests/unit/issues/issue-384-scheduled-grouping-bug.test.ts
- ensure date-only overdue checks compare UTC anchors instead of local midnight
- add regression test covering issue #384 scenario (UTC-8 user)
- npm run test:unit
=> Fix scheduled grouping for today

src/ui/FilterBar.ts, src/views/KanbanView.ts
Fixes kanban view column ordering persistence, default grouping behavior, and save view modal functionality.
- **#689**: Kanban view loses columns after upgrade
- **#679**: Clearing filters defaults to "none" instead of "status" grouping  
- **#710**: Column order changes when switching between views
- **Save view modal**: Modal opens blank, unable to save views
- **Per-grouping column persistence**: Each grouping type maintains separate column orders
- **Smart default ordering**: Status follows StatusManager order, priority follows weight order
- **Context-aware grouping**: Kanban defaults to "status", other views to "none" when cleared
- **Save modal improvements**: Added accessible button, fixed blank modal issue, improved styling
- **Migration logic**: Preserves existing users' column …
=> Fix kanban column ordering and view persistence issues

src/views/AdvancedCalendarView.ts, tests/unit/issues/issue-564-multi-day-task-creation.test.ts
Fixes issue #564 where dragging across multiple days in month/year view created tasks with 0 time estimate instead of reflecting the selected duration.
- Modified `handleTaskCreation` in `AdvancedCalendarView.ts` to calculate time estimate for multi-day all-day selections
- Multi-day selections now set time estimate as `days * 1440 minutes`
- Single-day all-day selections continue using default time estimate setting
- Added comprehensive test coverage
Closes #564
=> Fix multi-day task creation in month/year view

src/views/AgendaView.ts, tests/unit/issues/issue-695-agenda-ics-all-day-dup.test.ts
- adjust AgendaView ICS filtering to treat all-day exclusive end times as inclusive
- add regression test covering issue #695 
- npm run test -- --runInBand tests/unit/issues/issue-695-agenda-ics-all-day-dup.test.ts
=> Fix agenda duplication for all-day ICS events

build-css.mjs, src/editor/TaskCardNoteDecorations.ts, src/i18n/resources/en.ts, src/main.ts, src/services/TaskService.ts, src/settings/defaults.ts, src/settings/tabs/appearanceTab.ts, src/types/settings.ts, src/utils/templateProcessor.ts, styles/task-card-note-widget.css, tests/unit/services/TaskService.test.ts, tests/unit/utils/templateProcessor.test.ts
Implements a configurable task card widget that displays at the top of task notes, providing immediate access to task actions and context menus without requiring the command palette.
- Add TaskCardNoteDecorations extension using CodeMirror widget system
- Task card displays at top of note after frontmatter when present
- Uses existing createTaskCard function for consistency with other views
- Add showTaskCardInNote setting (enabled by default)
- Ensure task card appears above project subtasks widget when both enabled
- Minimal styling with border and small padding
- Responds to task updates, deletions, and settings changes
- CodeMirror WidgetType for rendering task card
- Automatic detection of task files using existing cache manager
- Live preview mode only (not shown in source mode)
- …
=> Add task card widget in task notes

src/services/TaskService.ts, src/utils/filenameGenerator.ts, tests/__mocks__/utils.ts
- Fix issue where POST /api/tasks returned original unsanitized title while task file used sanitized version
- Add title sanitization to TaskService.createTask() for consistent behavior
- Export sanitizeForFilename function and add test mock support
The HTTP API's POST /api/tasks endpoint was returning the original unsanitized title in the response, while the actual task file created used a sanitized title with problematic characters removed. This inconsistency caused confusion when the API response didn't match what was actually stored.
- Added `sanitizeTitle()` method to TaskService that removes problematic characters
- Modified `createTask()` to sanitize the title before using it throughout the process
- Exported `sanitizeForFilename` function for broader use
- Added mock …
=> Fix HTTP API task creation response consistency

src/suggest/FileSuggestHelper.ts, src/utils/FilterUtils.ts, src/utils/MinimalNativeCache.ts
Implements hierarchical tag support for Obsidian nested tags as requested in issue #584.
- **Hierarchical matching**: Searching for `t/ef` now matches child tags like `t/ef/project`, `t/ef/task`, `t/ef/bug`
- **Exclusion patterns**: Support for `-t/ef/bug` to exclude specific tags and their children
- **Backward compatibility**: Existing substring matching preserved (e.g., `proj` still matches `project/alpha`)
- Enhanced `FilterUtils` with `matchesHierarchicalTag()` and `matchesTagConditions()` methods
- Updated FilterBar tag filtering to use hierarchical matching for "contains" operations
- Enhanced project autosuggester required tags filtering
- Improved task identification by tags with hierarchical support
- All existing tests pass
- TypeScript compilation succeeds
- Manual testing …
=> feat: add hierarchical tag support with exclusion patterns

docs/releases/unreleased.md, src/modals/ProjectSelectModal.ts, src/modals/UnscheduledTasksSelectorModal.ts, src/services/AutoArchiveService.ts, src/services/StatusSuggestionService.ts, src/services/TaskService.ts, src/services/TaskStatsService.ts, src/services/ViewPerformanceService.ts, src/settings/components/CardComponent.ts, src/settings/tabs/integrationsTab.ts, src/settings/tabs/taskPropertiesTab.ts, src/suggest/FileSuggestHelper.ts, src/ui/FilterBar.ts, src/ui/TaskCard.ts, src/ui/renderers/linkRenderer.ts, src/utils/FilterUtils.ts, src/utils/MinimalNativeCache.ts, src/utils/filenameGenerator.ts, src/utils/helpers.ts, src/utils/viewOptimizations.ts, src/views/AdvancedCalendarView.ts, src/views/AgendaView.ts, src/views/KanbanView.ts, src/views/TaskListView.ts
Fixes #766 where tags containing "task" (like "pkm-task") were incorrectly identifying notes as task notes due to substring matching fallback in tag parsing.
- **Core Fix**: Added `FilterUtils.matchesHierarchicalTagExact()` for precise task identification
- **Updated Logic**: Modified `MinimalNativeCache.isTaskFile()` to use exact matching instead of substring fallback
- **Preserved Functionality**: Maintained substring matching for filter bar searches where it's desired
- **Code Quality**: Fixed all linting errors (41 errors eliminated, warnings remain)
- Only exact tag matches or hierarchical children (like "task/work") now identify notes as tasks
- Prevents false positives from tags like "pkm-task", "important-task", etc.
- Maintains proper hierarchical tag support
- Improves codebase …
=> Fix tag parsing false positives for task identification (#766)

docs/releases/unreleased.md, src/utils/MinimalNativeCache.ts, tests/utils/MinimalNativeCache.isTaskFile.test.ts
Fixes #776 - screens failing to load when frontmatter tags array contains non-string values.
- Added type validation in `MinimalNativeCache.ts` to filter out non-string values before calling string methods
- Updated changelog
- Verified fix handles frontmatter with mixed tag types (strings, numbers, booleans)
- Confirmed valid string tags continue to work normally
=> Fix screens failing to load with non-string tags

styles/task-card-note-widget.css
Mimics the css for project-note-subtasks widget for the cursor related issues to hide the cursor above the task card widget
=> Add cursor hiding css for task-card-note-widget

docs/releases/unreleased.md, src/services/FilterService.ts
Fixes #768 - Calendar view appearing empty due to crashes when sorting tasks with null values in grouping fields.
The calendar view was crashing with the error:
```
TypeError: Cannot read properties of null (reading 'localeCompare')
```
This occurred when tasks had null values in fields used for grouping (tags, contexts, projects, custom fields). The `sortGroups()` and `sortUserFieldGroups()` methods in FilterService were calling `localeCompare()` on potentially null values without checking.
Added null/undefined checks before all `localeCompare()` calls in the sorting logic:
- `sortGroups()` method: project, tags, completedDate, and default (contexts) cases
- `sortUserFieldGroups()` method: number, boolean, date, text, and list cases
Null values now sort to the end of groups (return 1 …
=> Fix calendar view crashes from null values in grouping fields (#768)

docs/releases/unreleased.md, src/bases/base-view-factory.ts, src/bases/kanban-view.ts
Fixes #806
Bases views (Task List and Kanban) crashed on Obsidian 1.10.0 startup when restoring from previous session with error: `TypeError: n.focus is not a function`
- Added defensive checks in `setEphemeralState` for DOM readiness
- Added `focus()` method to view objects
- Made root elements focusable with `tabIndex=-1`
Views now restore correctly on startup without crashes.
=> fix: Bases view crash on Obsidian 1.10.0 startup

docs/releases/unreleased.md, src/services/ICSNoteService.ts, src/services/TaskService.ts, src/utils/folderTemplateProcessor.ts, tests/__mocks__/date-fns.ts, tests/unit/services/ICSNoteService.folder-template.test.ts, tests/unit/utils/folderTemplateProcessor.test.ts
Fixes #816 - ICS subscription note folder paths now support template variables like `{{year}}`, `{{month}}`, `{{date}}`.
- Extracted folder template processing into shared utility (`src/utils/folderTemplateProcessor.ts`)
- Updated `ICSNoteService` to process folder template variables
- Refactored `TaskService` to use shared utility for consistency
- Added ICS-specific variables: `{{icsEventTitle}}`, `{{icsEventLocation}}`, `{{icsEventDescription}}`
- Enhanced date-fns mock to support all format strings
User can now configure:
```
Default note folder: Daily/{{year}}/{{month}}/
```
Which creates notes in: `Daily/2025/10/`
- 28 new tests for folder template processor utility
- 11 new tests for ICS folder template integration  
- All existing tests passing (1264 tests)
- No regressions …
=> fix: process template variables in ICS note folder paths (#816)

build-css.mjs, docs/releases/unreleased.md, src/bases/api.ts, src/bases/base-view-factory.ts, src/bases/helpers.ts, src/bases/kanban-view.ts, src/bases/registration.ts, src/main.ts, styles/bases-views.css
- Migrates Bases integration to use the public API (Bases 1.10.0+) with graceful fallback to internal API for older versions
- Adds grouped rendering support for both list and kanban views
- Fixes multiple UI issues including chevron rotation, drag-drop reliability, and view flickering
- Reduces console logging verbosity
=> feat: migrate Bases integration to public API with grouped view support

docs/releases/unreleased.md, issue-analysis/issue-826.md, src/editor/TaskCardNoteDecorations.ts, tests/unit/editor/TaskCardNoteDecorations.test.ts
Fixes #826 - Task card widget now appears correctly when Obsidian starts with a task note already open.
When Obsidian starts with a task note open, the `TaskCardNoteDecorationsPlugin` constructor is called during an active EditorView update cycle. The plugin uses synchronous data loading (`getCachedTaskInfoSync()`), which triggers an immediate `view.dispatch()` call during construction, causing the error: "Calls to EditorView.update are not allowed while an update is in progress."
Wrapped `view.dispatch()` in `queueMicrotask()` to defer the dispatch until after the current update cycle completes. This matches the natural deferral behavior of `ProjectNoteDecorations` which uses async data loading.
- Modified `dispatchUpdate()` method to use `queueMicrotask()` for deferred dispatch
- …
=> fix: task card widget not appearing on Obsidian startup (#826)

src/bases/calendar-view.ts, styles/advanced-calendar-view.css
Fixes calendar base view rendering and functionality in embedded Bases contexts.
- **Property access**: Add fallback from `getAsPropertyId()` to `get()` for embedded views where property configuration may not work correctly
- **Initialization**: Improve DOM readiness detection with `offsetParent` checks and longer retry delays (100ms) for embedded contexts  
- **Dimensions**: Set minimum heights (800px root, 700px calendar) to ensure proper rendering
- **Width expansion**: Add CSS rules forcing FullCalendar tables to fill container width, fixing narrow day columns
- **Size recalculation**: Call `calendar.updateSize()` after render to recalculate dimensions once DOM settles
- **FullCalendar options**: Add `expandRows`, `handleWindowResize`, and `stickyHeaderDates` for better embedded …
=> fix: calendar base view support for embedded views

tests/unit/issues/issue-810-overdue-tasks-disappear.test.ts
The `issue-810-overdue-tasks-disappear.test.ts` tests were failing when run after October 6, 2025 because:
1. Tests use a fixed date: `new Date(Date.UTC(2025, 9, 6))` (Oct 6, 2025)
2. The `isOverdueTimeAware()` function calls `getTodayString()` which uses the **real system date**
3. When run on any date after Oct 6, 2025, tasks due on Oct 6 would appear overdue
4. This caused the assertions to fail: tasks due "today" were incorrectly appearing in the overdue section
Mock the system date in the test suite using Jest's built-in time mocking:
- Added `jest.useFakeTimers()` and `jest.setSystemTime()` in `beforeEach()`
- Set system time to Oct 6, 2025 12:00 UTC (the test's "today")
- Added `jest.useRealTimers()` in `afterEach()` to clean up
This ensures consistent test behavior regardless of …
=> fix: mock system date in issue #810 tests
